spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_SERVER_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    hikari:
      maximum-pool-size: 30
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format-sql: true
        show: true

logging:
  level:
    org:
      hibernate:
        SQL: ${DEBUG_LEVEL}
        type:
          descriptor:
            BasicBinder: ${DEBUG_LEVEL}
            sql: error
      springframework.web: ${DEBUG_LEVEL}
    root: ${DEBUG_LEVEL}


server:
  port: 8080